version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment: 
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - user-data:/var/lib/postgresql/data/
    networks:
      - freaky
  api:
    container_name: api
    build: api/
    ports:
      - "8080:8080"
    networks:
      - freaky
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:docker@db:5432/my_database
    volumes:
      - type: bind
        source: ./api/src
        target: /src/app/src
  ui:
    container_name: ui
    build: ui/
    ports:
      - "3000:3000"
    networks:
      - freaky
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./ui/src
        target: /app/src
      
networks:
  freaky:
    driver: bridge

volumes:
  user-data: 