/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */

// const randCity = () => {
//   const iC = math.floor(math.random()*9) +1
//   for (let i = 0; i< recorderC.length(); i++){
//     if recorderA[i] 
//   }
// }
// const randAct = []

// let recorderC = []
// let recorderA = []

exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('city_activity').del()
  await knex('city_activity').insert([
    {city_id: 1, activities_id: 1},
    {city_id: 1, activities_id: 2},
    {city_id: 1, activities_id: 3},
    {city_id: 1, activities_id: 4},
    {city_id: 1, activities_id: 5},
    {city_id: 1, activities_id: 6},
    {city_id: 1, activities_id: 7},
    {city_id: 1, activities_id: 8},
    {city_id: 1, activities_id: 9},
    {city_id: 1, activities_id: 10},
    {city_id: 1, activities_id: 11},
    {city_id: 1, activities_id: 12},
    {city_id: 1, activities_id: 13},
    {city_id: 1, activities_id: 14},
    {city_id: 1, activities_id: 15},
    {city_id: 1, activities_id: 16},
    {city_id: 1, activities_id: 17},
    {city_id: 1, activities_id: 18},
    {city_id: 1, activities_id: 19},
    {city_id: 1, activities_id: 20},
    {city_id: 1, activities_id: 21},
    {city_id: 1, activities_id: 23},
    {city_id: 1, activities_id: 24},
    {city_id: 1, activities_id: 25},
    {city_id: 1, activities_id: 26},
    {city_id: 1, activities_id: 27},
    {city_id: 1, activities_id: 28},
    {city_id: 1, activities_id: 29},
    
    {city_id: 2, activities_id: 1},
    {city_id: 2, activities_id: 2},
    //{city_id: 2, activities_id: 3},
    {city_id: 2, activities_id: 4},
    //{city_id: 2, activities_id: 5},
    {city_id: 2, activities_id: 6},
    //{city_id: 2, activities_id: 7},
    {city_id: 2, activities_id: 8},
    {city_id: 2, activities_id: 9},
    {city_id: 2, activities_id: 10},
    {city_id: 2, activities_id: 11},
    {city_id: 2, activities_id: 12},
    {city_id: 2, activities_id: 13},
    //{city_id: 2, activities_id: 14},
    {city_id: 2, activities_id: 15},
    //{city_id: 2, activities_id: 16},
    {city_id: 2, activities_id: 17},
    {city_id: 2, activities_id: 18},
    {city_id: 2, activities_id: 19},
    {city_id: 2, activities_id: 20},
    //{city_id: 2, activities_id: 21},
    //{city_id: 2, activities_id: 23},
    {city_id: 2, activities_id: 24},
    //{city_id: 2, activities_id: 25},
    {city_id: 2, activities_id: 26},
    {city_id: 2, activities_id: 27},
    {city_id: 2, activities_id: 28},
    {city_id: 2, activities_id: 29},

    {city_id: 3, activities_id: 1},
    {city_id: 3, activities_id: 2},
    {city_id: 3, activities_id: 3},
    {city_id: 3, activities_id: 4},
    {city_id: 3, activities_id: 5},
    {city_id: 3, activities_id: 6},
    {city_id: 3, activities_id: 7},
    {city_id: 3, activities_id: 8},
    {city_id: 3, activities_id: 9},
    {city_id: 3, activities_id: 10},
    //{city_id: 3, activities_id: 11},
    {city_id: 3, activities_id: 12},
    {city_id: 3, activities_id: 13},
    //{city_id: 3, activities_id: 14},
    {city_id: 3, activities_id: 15},
    //{city_id: 3, activities_id: 16},
    {city_id: 3, activities_id: 17},
    //{city_id: 3, activities_id: 18},
    //{city_id: 3, activities_id: 19},
    //{city_id: 3, activities_id: 20},
    //{city_id: 3, activities_id: 21},
    //{city_id: 3, activities_id: 23},
    {city_id: 3, activities_id: 24},
    {city_id: 3, activities_id: 25},
    {city_id: 3, activities_id: 26},
    {city_id: 3, activities_id: 27},
    {city_id: 3, activities_id: 28},
    {city_id: 3, activities_id: 29},

    {city_id: 4, activities_id: 1},
    {city_id: 4, activities_id: 2},
    {city_id: 4, activities_id: 3},
    {city_id: 4, activities_id: 4},
    {city_id: 4, activities_id: 5},
    {city_id: 4, activities_id: 6},
    {city_id: 4, activities_id: 7},
    {city_id: 4, activities_id: 8},
    // {city_id: 4, activities_id: 9},
    {city_id: 4, activities_id: 10},
    {city_id: 4, activities_id: 11},
    {city_id: 4, activities_id: 12},
    {city_id: 4, activities_id: 13},
    {city_id: 4, activities_id: 14},
    {city_id: 4, activities_id: 15},
    {city_id: 4, activities_id: 16},
    {city_id: 4, activities_id: 17},
    // {city_id: 4, activities_id: 18},
    //{city_id: 4, activities_id: 19},
    {city_id: 4, activities_id: 20},
    {city_id: 4, activities_id: 21},
    // {city_id: 4, activities_id: 23},
    // {city_id: 4, activities_id: 24},
    {city_id: 4, activities_id: 25},
    {city_id: 4, activities_id: 26},
    {city_id: 4, activities_id: 27},
    {city_id: 4, activities_id: 28},
    //{city_id: 4, activities_id: 29},
    
    {city_id: 5, activities_id: 1},
    {city_id: 5, activities_id: 2},
    //{city_id: 5, activities_id: 3},
    //{city_id: 5, activities_id: 4},
    //{city_id: 5, activities_id: 5},
    {city_id: 5, activities_id: 6},
    {city_id: 5, activities_id: 7},
    {city_id: 5, activities_id: 8},
    {city_id: 5, activities_id: 9},
    //{city_id: 5, activities_id: 10},
    {city_id: 5, activities_id: 11},
    {city_id: 5, activities_id: 12},
    //{city_id: 5, activities_id: 13},
    {city_id: 5, activities_id: 14},
    //{city_id: 5, activities_id: 15},
    {city_id: 5, activities_id: 16},
    {city_id: 5, activities_id: 17},
    {city_id: 5, activities_id: 18},
    {city_id: 5, activities_id: 19},
    {city_id: 5, activities_id: 20},
    {city_id: 5, activities_id: 21},
    {city_id: 5, activities_id: 23},
    {city_id: 5, activities_id: 24},
    {city_id: 5, activities_id: 25},
    {city_id: 5, activities_id: 26},
    {city_id: 5, activities_id: 27},
    {city_id: 5, activities_id: 28},
    {city_id: 5, activities_id: 29},
    
    //{city_id: 6, activities_id: 1},
    {city_id: 6, activities_id: 2},
    //{city_id: 6, activities_id: 3},
    //{city_id: 6, activities_id: 4},
    //{city_id: 6, activities_id: 5},
    {city_id: 6, activities_id: 6},
    {city_id: 6, activities_id: 7},
    {city_id: 6, activities_id: 8},
    {city_id: 6, activities_id: 9},
    {city_id: 6, activities_id: 10},
    {city_id: 6, activities_id: 11},
    {city_id: 6, activities_id: 12},
    {city_id: 6, activities_id: 13},
    //{city_id: 6, activities_id: 14},
    {city_id: 6, activities_id: 15},
    {city_id: 6, activities_id: 16},
    //{city_id: 6, activities_id: 17},
    {city_id: 6, activities_id: 18},
    //{city_id: 6, activities_id: 19},
    {city_id: 6, activities_id: 20},
    //{city_id: 6, activities_id: 21},
    //{city_id: 6, activities_id: 23},
    {city_id: 6, activities_id: 24},
    {city_id: 6, activities_id: 25},
    {city_id: 6, activities_id: 26},
    {city_id: 6, activities_id: 27},
    {city_id: 6, activities_id: 28},
    {city_id: 6, activities_id: 29},
    
    //{city_id: 7, activities_id: 1},
    {city_id: 7, activities_id: 2},
    {city_id: 7, activities_id: 3},
    {city_id: 7, activities_id: 4},
    {city_id: 7, activities_id: 5},
    //{city_id: 7, activities_id: 6},
    {city_id: 7, activities_id: 7},
    {city_id: 7, activities_id: 8},
    {city_id: 7, activities_id: 9},
    {city_id: 7, activities_id: 10},
    //{city_id: 7, activities_id: 11},
    {city_id: 7, activities_id: 12},
    {city_id: 7, activities_id: 13},
    {city_id: 7, activities_id: 14},
    {city_id: 7, activities_id: 15},
    //{city_id: 7, activities_id: 16},
    //{city_id: 7, activities_id: 17},
    {city_id: 7, activities_id: 18},
    {city_id: 7, activities_id: 19},
    {city_id: 7, activities_id: 20},
    //{city_id: 7, activities_id: 21},
    {city_id: 7, activities_id: 23},
    //{city_id: 7, activities_id: 24},
    {city_id: 7, activities_id: 25},
    {city_id: 7, activities_id: 26},
    //{city_id: 7, activities_id: 27},
    //{city_id: 7, activities_id: 28},
    {city_id: 7, activities_id: 29},
    
    {city_id: 8, activities_id: 1},
    //{city_id: 8, activities_id: 2},
    {city_id: 8, activities_id: 3},
    // {city_id: 8, activities_id: 4},
    {city_id: 8, activities_id: 5},
    {city_id: 8, activities_id: 6},
    {city_id: 8, activities_id: 7},
    {city_id: 8, activities_id: 8},
    {city_id: 8, activities_id: 9},
    {city_id: 8, activities_id: 10},
    // {city_id: 8, activities_id: 11},
    {city_id: 8, activities_id: 12},
    //{city_id: 8, activities_id: 13},
    //{city_id: 8, activities_id: 14},
    //{city_id: 8, activities_id: 15},
    //{city_id: 8, activities_id: 16},
    //{city_id: 8, activities_id: 17},
    {city_id: 8, activities_id: 18},
    {city_id: 8, activities_id: 19},
    {city_id: 8, activities_id: 20},
    // {city_id: 8, activities_id: 21},
    {city_id: 8, activities_id: 23},
    {city_id: 8, activities_id: 24},
    {city_id: 8, activities_id: 25},
    {city_id: 8, activities_id: 26},
    {city_id: 8, activities_id: 27},
    // {city_id: 8, activities_id: 28},
    {city_id: 8, activities_id: 29},
    
    {city_id: 9, activities_id: 1},
    {city_id: 9, activities_id: 2},
    {city_id: 9, activities_id: 3},
    {city_id: 9, activities_id: 4},
    {city_id: 9, activities_id: 5},
    {city_id: 9, activities_id: 6},
    {city_id: 9, activities_id: 7},
    {city_id: 9, activities_id: 8},
    {city_id: 9, activities_id: 9},
    {city_id: 9, activities_id: 10},
    {city_id: 9, activities_id: 11},
    {city_id: 9, activities_id: 12},
    //{city_id: 9, activities_id: 13},
    //{city_id: 9, activities_id: 14},
    {city_id: 9, activities_id: 15},
    //{city_id: 9, activities_id: 16},
    {city_id: 9, activities_id: 17},
    //{city_id: 9, activities_id: 18},
    {city_id: 9, activities_id: 19},
    {city_id: 9, activities_id: 20},
    {city_id: 9, activities_id: 21},
    {city_id: 9, activities_id: 23},
    //{city_id: 9, activities_id: 24},
    {city_id: 9, activities_id: 25},
    {city_id: 9, activities_id: 26},
    {city_id: 9, activities_id: 27},
    {city_id: 9, activities_id: 28},
    {city_id: 9, activities_id: 29},
  ]);
};
